# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(844, 709)
        MainWindow.setStyleSheet("background-color: rgb(68, 68, 80);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.browseButton = QtWidgets.QPushButton(self.frame_3)
        self.browseButton.setMinimumSize(QtCore.QSize(0, 50))
        self.browseButton.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.browseButton.setObjectName("browseButton")
        self.verticalLayout_3.addWidget(self.browseButton)
        self.saveButton = QtWidgets.QPushButton(self.frame_3)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 50))
        self.saveButton.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_3.addWidget(self.saveButton)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(220, 220, 220);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.alignButton_10 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_10.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_10.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_10.setObjectName("alignButton_10")
        self.gridLayout.addWidget(self.alignButton_10, 1, 0, 1, 1)
        self.alignButton_20 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_20.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_20.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_20.setObjectName("alignButton_20")
        self.gridLayout.addWidget(self.alignButton_20, 2, 0, 1, 1)
        self.alignButton_00 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_00.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_00.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_00.setObjectName("alignButton_00")
        self.gridLayout.addWidget(self.alignButton_00, 0, 0, 1, 1)
        self.alignButton_01 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_01.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_01.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_01.setObjectName("alignButton_01")
        self.gridLayout.addWidget(self.alignButton_01, 0, 1, 1, 1)
        self.alignButton_02 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_02.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_02.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_02.setObjectName("alignButton_02")
        self.gridLayout.addWidget(self.alignButton_02, 0, 2, 1, 1)
        self.alignButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_11.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_11.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_11.setObjectName("alignButton_11")
        self.gridLayout.addWidget(self.alignButton_11, 1, 1, 1, 1)
        self.alignButton_12 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_12.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_12.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_12.setObjectName("alignButton_12")
        self.gridLayout.addWidget(self.alignButton_12, 1, 2, 1, 1)
        self.alignButton_21 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_21.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_21.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_21.setObjectName("alignButton_21")
        self.gridLayout.addWidget(self.alignButton_21, 2, 1, 1, 1)
        self.alignButton_22 = QtWidgets.QPushButton(self.frame_5)
        self.alignButton_22.setMinimumSize(QtCore.QSize(35, 35))
        self.alignButton_22.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.alignButton_22.setObjectName("alignButton_22")
        self.gridLayout.addWidget(self.alignButton_22, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(125, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(220, 220, 220);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(220, 220, 220);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBox_up = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox_up.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_up.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.spinBox_up.setObjectName("spinBox_up")
        self.horizontalLayout.addWidget(self.spinBox_up)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(220, 220, 220);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_down = QtWidgets.QSpinBox(self.frame_8)
        self.spinBox_down.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_down.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.spinBox_down.setObjectName("spinBox_down")
        self.horizontalLayout_3.addWidget(self.spinBox_down)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(220, 220, 220);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox_left = QtWidgets.QSpinBox(self.frame_9)
        self.spinBox_left.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_left.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.spinBox_left.setObjectName("spinBox_left")
        self.horizontalLayout_4.addWidget(self.spinBox_left)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(220, 220, 220);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinBox_right = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox_right.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_right.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.spinBox_right.setObjectName("spinBox_right")
        self.horizontalLayout_5.addWidget(self.spinBox_right)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ComboBox_font = QtWidgets.QFontComboBox(self.frame_14)
        self.ComboBox_font.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComboBox_font.setFont(font)
        self.ComboBox_font.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.ComboBox_font.setObjectName("ComboBox_font")
        self.horizontalLayout_6.addWidget(self.ComboBox_font)
        self.comboBox_fontsize = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_fontsize.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_fontsize.setFont(font)
        self.comboBox_fontsize.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.comboBox_fontsize.setFrame(True)
        self.comboBox_fontsize.setObjectName("comboBox_fontsize")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.comboBox_fontsize.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_fontsize)
        self.verticalLayout_7.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.boldButton = QtWidgets.QPushButton(self.frame_13)
        self.boldButton.setMinimumSize(QtCore.QSize(35, 35))
        self.boldButton.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boldButton.setFont(font)
        self.boldButton.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout_7.addWidget(self.boldButton)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_14.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_14.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_7.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_15.setMinimumSize(QtCore.QSize(70, 35))
        self.pushButton_15.setMaximumSize(QtCore.QSize(70, 35))
        self.pushButton_15.setText("")
        self.pushButton_15.setCheckable(False)
        self.pushButton_15.setAutoRepeat(False)
        self.pushButton_15.setAutoExclusive(False)
        self.pushButton_15.setAutoRepeatInterval(100)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_7.addWidget(self.pushButton_15)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(220, 220, 220);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(98, 98, 115);")
        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.previewButton = QtWidgets.QPushButton(self.frame_2)
        self.previewButton.setMinimumSize(QtCore.QSize(0, 35))
        self.previewButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.previewButton.setStyleSheet("background-color: rgb(249, 201, 91);")
        self.previewButton.setObjectName("previewButton")
        self.verticalLayout_2.addWidget(self.previewButton)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.browseButton.clicked.connect(MainWindow.eventBrowseImg)
        self.saveButton.clicked.connect(MainWindow.eventSaveImg)
        self.previewButton.clicked.connect(MainWindow.eventPreview)
        self.alignButton_00.clicked.connect(MainWindow.eventAlign00)
        self.alignButton_01.clicked.connect(MainWindow.eventAlign01)
        self.alignButton_02.clicked.connect(MainWindow.eventAlign02)
        self.alignButton_10.clicked.connect(MainWindow.eventAlign10)
        self.alignButton_11.clicked.connect(MainWindow.eventAlign11)
        self.alignButton_12.clicked.connect(MainWindow.eventAlign12)
        self.alignButton_20.clicked.connect(MainWindow.eventAlign20)
        self.alignButton_21.clicked.connect(MainWindow.eventAlign21)
        self.alignButton_22.clicked.connect(MainWindow.eventAlign22)
        self.boldButton.clicked.connect(MainWindow.eventBold)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browseButton.setText(_translate("MainWindow", "開啟檔案"))
        self.saveButton.setText(_translate("MainWindow", "另存新檔"))
        self.label_2.setText(_translate("MainWindow", "對齊方式:"))
        self.alignButton_10.setText(_translate("MainWindow", "左"))
        self.alignButton_20.setText(_translate("MainWindow", "左下"))
        self.alignButton_00.setText(_translate("MainWindow", "中左"))
        self.alignButton_01.setText(_translate("MainWindow", "中上"))
        self.alignButton_02.setText(_translate("MainWindow", "中右"))
        self.alignButton_11.setText(_translate("MainWindow", "中"))
        self.alignButton_12.setText(_translate("MainWindow", "右"))
        self.alignButton_21.setText(_translate("MainWindow", "中下"))
        self.alignButton_22.setText(_translate("MainWindow", "右下"))
        self.label_3.setText(_translate("MainWindow", "微調:"))
        self.label_4.setText(_translate("MainWindow", "上"))
        self.label_5.setText(_translate("MainWindow", "下"))
        self.label_6.setText(_translate("MainWindow", "左"))
        self.label_7.setText(_translate("MainWindow", "右"))
        self.comboBox_fontsize.setCurrentText(_translate("MainWindow", "8"))
        self.comboBox_fontsize.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_fontsize.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox_fontsize.setItemText(2, _translate("MainWindow", "12"))
        self.comboBox_fontsize.setItemText(3, _translate("MainWindow", "14"))
        self.comboBox_fontsize.setItemText(4, _translate("MainWindow", "16"))
        self.comboBox_fontsize.setItemText(5, _translate("MainWindow", "18"))
        self.comboBox_fontsize.setItemText(6, _translate("MainWindow", "20"))
        self.comboBox_fontsize.setItemText(7, _translate("MainWindow", "22"))
        self.comboBox_fontsize.setItemText(8, _translate("MainWindow", "24"))
        self.comboBox_fontsize.setItemText(9, _translate("MainWindow", "26"))
        self.comboBox_fontsize.setItemText(10, _translate("MainWindow", "28"))
        self.comboBox_fontsize.setItemText(11, _translate("MainWindow", "30"))
        self.comboBox_fontsize.setItemText(12, _translate("MainWindow", "32"))
        self.comboBox_fontsize.setItemText(13, _translate("MainWindow", "34"))
        self.comboBox_fontsize.setItemText(14, _translate("MainWindow", "36"))
        self.comboBox_fontsize.setItemText(15, _translate("MainWindow", "38"))
        self.comboBox_fontsize.setItemText(16, _translate("MainWindow", "40"))
        self.comboBox_fontsize.setItemText(17, _translate("MainWindow", "42"))
        self.comboBox_fontsize.setItemText(18, _translate("MainWindow", "44"))
        self.comboBox_fontsize.setItemText(19, _translate("MainWindow", "46"))
        self.comboBox_fontsize.setItemText(20, _translate("MainWindow", "48"))
        self.comboBox_fontsize.setItemText(21, _translate("MainWindow", "50"))
        self.comboBox_fontsize.setItemText(22, _translate("MainWindow", "52"))
        self.comboBox_fontsize.setItemText(23, _translate("MainWindow", "54"))
        self.comboBox_fontsize.setItemText(24, _translate("MainWindow", "56"))
        self.comboBox_fontsize.setItemText(25, _translate("MainWindow", "58"))
        self.comboBox_fontsize.setItemText(26, _translate("MainWindow", "60"))
        self.boldButton.setText(_translate("MainWindow", "B"))
        self.pushButton_14.setText(_translate("MainWindow", "I"))
        self.label_8.setText(_translate("MainWindow", "文字:"))
        self.previewButton.setText(_translate("MainWindow", "預覽"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
